package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StudentTeam generated by hbm2java
 */
public class StudentTeam implements java.io.Serializable {

	private StudentTeamId id;
	private Teacher teacher;
	private Team team;
	private Student student;
	private Date enrollmentDate;

	public StudentTeam() {
	}

	public StudentTeam(StudentTeamId id, Team team,
			Student student) {
		this.id = id;
		this.team = team;
		this.student = student;
	}

	public StudentTeam(StudentTeamId id, EventInstance eventInstance,
			Teacher teacher, Team team, Student student, Date enrollmentDate) {
		this.id = id;
		this.teacher = teacher;
		this.team = team;
		this.student = student;
		this.enrollmentDate = enrollmentDate;
	}

	public StudentTeamId getId() {
		return this.id;
	}

	public void setId(StudentTeamId id) {
		this.id = id;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getEnrollmentDate() {
		return this.enrollmentDate;
	}

	public void setEnrollmentDate(Date enrollmentDate) {
		this.enrollmentDate = enrollmentDate;
	}

}
