package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * EventInstance generated by hbm2java
 */
public class EventInstance implements java.io.Serializable {

	private Integer id;
	private Event event;
	private Date createdDate;
	private Date startTime;
	private Date endTime;
	private String location;
	private Set teams;
	private int schoolId;
	
	public EventInstance() {
	}

	public EventInstance(Event event, Date startTime, Date endTime) {
		this.event = event;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public EventInstance(Event event, Date createdDate, Date startTime,
			Date endTime, String location, Integer schoolId) {
		this.event = event;
		this.createdDate = createdDate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.location = location;
		this.schoolId = schoolId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}
	public Set getTeams() {
		return teams;
	}

	public void setTeams(Set teams) {
		this.teams = teams;
	}
	
	public int getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}


}
