package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

	private Integer id;
	private Teacher teacher;
	private Role role;
	private String username;
	private String password;
	private String salt;
	private Date lastLoginDate;

	public Login() {
	}

	public Login(Teacher teacher, Role role, String username, String password) {
		this.teacher = teacher;
		this.role = role;
		this.username = username;
		this.password = password;
	}

	public Login(Teacher teacher, Role role, String username, String password,
			String salt, Date lastLoginDate) {
		this.teacher = teacher;
		this.role = role;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.lastLoginDate = lastLoginDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

}
