package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentEventTeamId generated by hbm2java
 */
public class StudentTeamId implements java.io.Serializable {

	private int studentId;
	private int teamId;

	public StudentTeamId() {
	}

	public StudentTeamId(int studentId, int teamId) {
		this.studentId = studentId;
		this.teamId = teamId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}


	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentTeamId))
			return false;
		StudentTeamId castOther = (StudentTeamId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& (this.getTeamId() == castOther.getTeamId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + this.getTeamId();
		return result;
	}

}
