package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private School school;
	private String firstName;
	private String lastName;
	private String middleName;
	private Date createDate;

	public Student() {
	}
	public Student(int studentId) {
		this.id = studentId;
	}
	public Student(School school, String firstName, String lastName) {
		this.school = school;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Student(School school, String firstName, String lastName,
			String middleName, Date createDate, Set studentTeams) {
		this.school = school;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	public String getFullName(){
		return firstName + " " + lastName;
	}

}
