package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StudentEventTeam generated by hbm2java
 */
public class StudentEventTeam implements java.io.Serializable {

	private StudentEventTeamId id;
	private Event event;
	private Teacher teacher;
	private Team team;
	private Student student;
	private Date enrollmentDate;

	public StudentEventTeam() {
	}

	public StudentEventTeam(StudentEventTeamId id, Event event, Team team,
			Student student) {
		this.id = id;
		this.event = event;
		this.team = team;
		this.student = student;
	}

	public StudentEventTeam(StudentEventTeamId id, Event event,
			Teacher teacher, Team team, Student student, Date enrollmentDate) {
		this.id = id;
		this.event = event;
		this.teacher = teacher;
		this.team = team;
		this.student = student;
		this.enrollmentDate = enrollmentDate;
	}

	public StudentEventTeamId getId() {
		return this.id;
	}

	public void setId(StudentEventTeamId id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getEnrollmentDate() {
		return this.enrollmentDate;
	}

	public void setEnrollmentDate(Date enrollmentDate) {
		this.enrollmentDate = enrollmentDate;
	}

}
