SET SQL_SAFE_UPDATES=0;
DELETE FROM StudentTeam;
DELETE FROM Team;
DELETE FROM Login;
DELETE FROM EventInstance;
DELETE FROM Event;
DELETE FROM Teacher;
DELETE FROM Student;
DELETE FROM EventType;
DELETE FROM School;
#INSERT INTO `fblaem`.`Role`(`RoleName`)VALUES("Administrator");
SET @AdminRole = (SELECT r.id FROM Role r where r.RoleName = "Administrator");
SET @UserRole = (SELECT r.id FROM Role r where r.RoleName = "Teacher");
#INSERT INTO `fblaem`.`Role`(`RoleName`)VALUES("Teacher");
INSERT INTO `fblaem`.`School`(`Name`,`StreetAddress`,`City`,`State`,`Zip`,`Phone`,`CreatedDate`)VALUES("Weber State","","Ogden","UT","84403","1234567890",now());
set @Weber = last_insert_id();
#INSERT INTO `fblaem`.`School`(`Name`,`StreetAddress`,`City`,`State`,`Zip`,`Phone`,`CreatedDate`)VALUES("Test School2","123 fake st","Layton","UT","84444","1234567890",now());
INSERT INTO `fblaem`.`Teacher`(`SchoolID`,`Email`,`FirstName`,`LastName`,`Phone`,`CreateDate`)VALUES(@Weber,"admin@admin.com","AdminUser","AdminUser","1234567890",now());
#INSERT INTO `fblaem`.`Teacher`(`SchoolID`,`Email`,`FirstName`,`LastName`,`Phone`,`CreateDate`)VALUES("2","teacher2@nowhere.com","TestTeacherfname","TestTeacherlname","1234567890",now());
#INSERT INTO `fblaem`.`Student`(`SchoolID`,`FirstName`,`LastName`,`CreateDate`)VALUES("1","testStudentfname","testStudentlname",now());
#INSERT INTO `fblaem`.`Student`(`SchoolID`,`FirstName`,`LastName`,`CreateDate`)VALUES("1","test2Studentfname","test2Studentlname",now());
#admin admin
INSERT INTO `fblaem`.`Login`(`RoleID`,`TeacherID`,`Username`,`Password`)VALUES(@AdminRole,LAST_INSERT_ID(),"admin","8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918");
INSERT INTO `fblaem`.`Teacher`(`SchoolID`,`Email`,`FirstName`,`LastName`,`Phone`,`CreateDate`)VALUES(@Weber,"admin@admin.com","Teacher","admin","1234567890",now());
INSERT INTO `fblaem`.`Login`(`RoleID`,`TeacherID`,`Username`,`Password`)VALUES(@UserRole,LAST_INSERT_ID(),"teacher","8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918");
INSERT INTO `fblaem`.`EventType`(`TypeName`)VALUES("Individual");
SET @Individual = last_insert_id();
INSERT INTO `fblaem`.`EventType`(`TypeName`)VALUES("Team");
SET @Team = last_insert_id();
INSERT INTO `fblaem`.`EventType`(`TypeName`)VALUES("Team/Individual");
SET @TeamIndividual = last_insert_id();
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Accounting I","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Accounting II","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Banking & Financial Systems","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Calculations","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Communication","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Ethics","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Law","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Math","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Presentation","1","3","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Business Procedures","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Client Service","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Computer Applications","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Computer Game & Simulation Program","1","3","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Computer Problem Solving","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Cyber Security","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Desktop Publishing","2","2","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Digital Design & Promotion","1","2","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Digital Video Production","1","3","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("E-business","1","3","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Economics","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Emerging Business Issues","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Entrepreneurship","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("FBLA Principles & Procedures","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Global Business","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Health Care Administration","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Help Desk","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Hospitality Management","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Impromptu Speaking","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Introduction to Business","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Introduction to Business Communication","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Introduction to Parliamentary Procedure","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Introduction to Technology Concepts","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Job Interview","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Management Decision Making","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Marketing","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Network Design","2","3","2",@Team,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Networking Concepts","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Parliamentary Procedures","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Personal Finance","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Public Speaking II","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Sports Management","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Spreadsheet Applications","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Technology Concepts","1","1","20",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Web Site Design","1","3","2",@TeamIndividual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Word Processing I","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
INSERT INTO `fblaem`.`Event`(`Name`,`MinTeamSize`,`MaxTeamSize`,`MaxEntriesPerSchool`,`EventTypeID`,`CreatedDate`)VALUES("Word Processing II","1","1","2",@Individual,now());
INSERT INTO `fblaem`.`EventInstance`(`EventID`,`CreatedDate`,`StartTime`,`Location`)VALUES(LAST_INSERT_ID(),now(),now(),"");
#-----
#INSERT INTO `fblaem`.`Team`(`Name`,`CreatedDate`,`EventInstanceID`)VALUES("test",now(),1);
#INSERT INTO `fblaem`.`Team`(`Name`,`CreatedDate`,`EventInstanceID`)VALUES("test",now(),2);