package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudentEventTeamId generated by hbm2java
 */
public class StudentEventTeamId implements java.io.Serializable {

	private int studentId;
	private int eventId;
	private int teamId;

	public StudentEventTeamId() {
	}

	public StudentEventTeamId(int studentId, int eventId, int teamId) {
		this.studentId = studentId;
		this.eventId = eventId;
		this.teamId = teamId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentEventTeamId))
			return false;
		StudentEventTeamId castOther = (StudentEventTeamId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& (this.getEventId() == castOther.getEventId())
				&& (this.getTeamId() == castOther.getTeamId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + this.getEventId();
		result = 37 * result + this.getTeamId();
		return result;
	}

}
