package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer id;
	private School school;
	private String email;
	private String firstName;
	private String lastName;
	private String phone;
	private String altPhone;
	private Date createDate;
	private Set logins = new HashSet(0);
	private Set studentTeams = new HashSet(0);

	public Teacher() {
	}

	public Teacher(School school, String email, String firstName,
			String lastName, String phone, String altPhone) {
		this.school = school;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.altPhone = altPhone;
	}

	public Teacher(School school, String email, String firstName,
			String lastName, String phone, String altPhone, Date createDate,
			Set logins, Set studentTeams) {
		this.school = school;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.altPhone = altPhone;
		this.createDate = createDate;
		this.logins = logins;
		this.studentTeams = studentTeams;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAltPhone() {
		return this.altPhone;
	}

	public void setAltPhone(String altPhone) {
		this.altPhone = altPhone;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set getLogins() {
		return this.logins;
	}

	public void setLogins(Set logins) {
		this.logins = logins;
	}

	public Set getstudentTeams() {
		return this.studentTeams;
	}

	public void setstudentTeams(Set studentTeams) {
		this.studentTeams = studentTeams;
	}
	
	public String getFullName() {
		return firstName + " " + lastName;
	}
}
