package edu.weber.ntm.fblaem.databaseio;

// Generated Nov 1, 2013 7:05:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable {

	private Integer id;
	private String name;
	private String maxIndividuals;
	private Date createdDate;
	private Set studentTeams = new HashSet(0);
	private Integer EventInstanceID;

	public Team() {
	}
	
	public Team(String name, String maxIndividuals, Date createdDate,
			Set studentTeams) {
		this.name = name;
		this.maxIndividuals = maxIndividuals;
		this.createdDate = createdDate;
		this.studentTeams = studentTeams;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMaxIndividuals() {
		return this.maxIndividuals;
	}

	public void setMaxIndividuals(String maxIndividuals) {
		this.maxIndividuals = maxIndividuals;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set getstudentTeams() {
		return this.studentTeams;
	}

	public void setstudentTeams(Set studentTeams) {
		this.studentTeams = studentTeams;
	}

	public Integer getEventInstanceID() {
		return EventInstanceID;
	}

	public void setEventInstanceID(Integer eventInstanceID) {
		EventInstanceID = eventInstanceID;
	}

}
